import type { Metadata } from "next";
import { DM_Mono, Space_Grotesk } from "next/font/google";
import { gothamBold } from './fonts'
import "./globals.css";

const dmMono = DM_Mono({
  subsets: ['latin'],
  weight: '300', // Light
  variable: '--font-dm-mono',
  display: 'swap',
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: '300', // Light
  variable: '--font-space-grotesk',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmMono.variable} ${spaceGrotesk.variable} ${gothamBold.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
